# Netlify configuration file

# Build settings
[build]
  command = "npm run build"
  publish = "dist"
  
# Secrets scanning settings
[build.processing.secrets]
  # Tell the scanner to ignore all JavaScript files inside the assets folder
  omit_paths = ["dist/assets/*.js"]